name: Merge Acceptance Checks
on:
  push:
    branches:
      - "*"
    pull_request:
      branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ">=17.3.0"
      - name: Install NPM packages
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Build app
        run: npm run build
